force-app/main/default/objects/Material__c/Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MT# {YY}{00000000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material__c/fields/NMU__c.field-meta.xml
<CustomField>
    <fullName>NMU__c</fullName>
    <label>NMU</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Material__c/fields/Werks__c.field-meta.xml
<CustomField>
    <fullName>Werks__c</fullName>
    <label>Werks</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test/InventoryLockTriggerTest.cls
@IsTest
public with sharing class InventoryLockTriggerTest {

//    intentar reservar por encima del disponible
//    intentar reservar por justo el disponible
//    intentar reservar por con reservas by serial
//    reservas en bulkP

@IsTest 
static void testReservasBulk() {
    Map<String,Material__c> materiales= TestDataFactory.getMateriales();

    try {
        // Intenta reservar el primero 

        // materiales.get(0).Nmu__c;
        // materiales.get(0).Werks__c;

    } catch ( Exception e) {

    }
 }




}