force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene cantidad total, reservas, muletos y disponibles de cada Punto de Venta / NMU</description>
    <label>Inventario</label>
    <nameField>
        <label>Werks y Nmu</label>
    </nameField>
    <pluralLabel>Inventarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/LockedByQuantity__c.field-meta.xml
<CustomField>
    <fullName>LockedByQuantity__c</fullName>
    <label>Bloqueos por Cantidad</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/mtpl__c.field-meta.xml
<CustomField>
    <fullName>mtpl__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad disponible</description>
    <label>Disponibles</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InventoryLock__c/InventoryLock__c.object-meta.xml
<CustomObject>
    <label>Bloqueo por Cantidad</label>
    <nameField>
        <displayFormat>IL# {YY}{00000000}</displayFormat>
        <label>InventoryLock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bloqueos por Cantidad</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InventoryLock__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>Bloqueos por Cantidad</relationshipLabel>
    <relationshipName>InventoryLock</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InventoryLock__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Cantidad de materiales bloqueados bajo este Id</description>
    <label>Cantidad</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InventoryLockTriggerHelper.cls
public with sharing class InventoryLockTriggerHelper {
    final static String ERROR_FALTA_DISPONIBILIDAD = 'No se puede reservar la cantidad {0} por que el maximo disponible es {1}';
    final static String ERROR_DE_INTEGRIDAD = 'El registro de Inventory no corresponde con los bloqueos de cantidad';

    public static Map<Id, Inventory__c> buscarInventarios(List<InventoryLock__c> reservas) {
        Set<Id> inventarios = TriggerHelper.getIdsFromSObjects(reservas, 'Inventory__c');
        return new Map<Id, Inventory__c>([SELECT LockedByQuantity__c, mtpl__c FROM Inventory__c WHERE Id IN :inventarios]);
    }

    public static void agregarReserva(List<InventoryLock__c> reservas) {

        Map<Id, Inventory__c> inventarios = buscarInventarios(reservas);

        for ( InventoryLock__c reserva :reservas ) {
            Inventory__c inventario = inventarios.get( reserva.Inventory__c );

            Double disponibleVenta = inventario.mtpl__c - inventario.LockedByQuantity__c; // Igual que la formula Available
            if ( disponibleVenta  >=  reserva.quantity__c ) {
                inventario.LockedByQuantity__c  += reserva.quantity__c;
            } else {
                reserva.addError( String.format(ERROR_FALTA_DISPONIBILIDAD, new Double[]{reserva.quantity__c, disponibleVenta }) );
            }
        }

        InventoryTriggerHandler.flagInventoryTrigger = true;
        update inventarios.values();
        InventoryTriggerHandler.flagInventoryTrigger = false;
    }

    public static void liberarReserva (List<InventoryLock__c> reservas) {
        Map<Id, Inventory__c> inventarios = buscarInventarios(reservas);

        for ( InventoryLock__c reserva :reservas ) {
            Inventory__c inventario = inventarios.get( reserva.Inventory__c );

            if ( inventario.LockedByQuantity__c  >=  reserva.quantity__c ) {
                inventario.LockedByQuantity__c  -= reserva.quantity__c;
            } else {
                reserva.addError( ERROR_DE_INTEGRIDAD );
            }
        }

        InventoryTriggerHandler.flagInventoryTrigger = true;
        update inventarios.values();    
        InventoryTriggerHandler.flagInventoryTrigger = false;
    }

}