force-app/main/default/objects/BusinessSite__c/BusinessSite__c.object-meta.xml
<CustomObject>
    <label>Punto de Venta</label>
    <nameField>
        <label>Business Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Puntos de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessSite__c/fields/Werks__c.field-meta.xml
<CustomField>
    <fullName>Werks__c</fullName>
    <label>Werks</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene cantidad total, reservas, muletos y disponibles de cada Punto de Venta / NMU</description>
    <label>Inventario</label>
    <nameField>
        <label>Werks y Nmu</label>
    </nameField>
    <pluralLabel>Inventarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <description>Cantidad disponible</description>
    <label>Disponibles</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/BusinessSite__c.field-meta.xml
<CustomField>
    <fullName>BusinessSite__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup a Business Site</description>
    <label>Punto de Venta</label>
    <referenceTo>BusinessSite__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup a Product</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <description>Cantidad total de materiales del NMU / Punto de venta</description>
    <label>Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Material__c/Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MT# {YY}{00000000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Material__c/fields/BusinessSite__c.field-meta.xml
<CustomField>
    <fullName>BusinessSite__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Site</label>
    <referenceTo>BusinessSite__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Material__c/fields/NMU__c.field-meta.xml
<CustomField>
    <fullName>NMU__c</fullName>
    <label>NMU</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Material__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Material__c/fields/Serial__c.field-meta.xml
<CustomField>
    <fullName>Serial__c</fullName>
    <description>Código único que identifica el material. En tipo &quot;Terminales&quot; se trata del IMEI. En tipo &quot;Simcard&quot; refiere al IMSI</description>
    <externalId>true</externalId>
    <label>Serial</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Material__c/fields/Werks__c.field-meta.xml
<CustomField>
    <fullName>Werks__c</fullName>
    <label>Werks</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NMU__c.field-meta.xml
<CustomField>
    <fullName>NMU__c</fullName>
    <label>NMU</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test/MaterialTriggerTest.cls
@IsTest
public with sharing class MaterialTriggerTest {

    @TestSetup
    static void createNMUyWerks() {
        TestDataFactory.makeProductos(true, 5);    
        TestDataFactory.makeBusinessSite(true, 5);    
    }

    @IsTest 
    static void testAltaDeMateriales() {
        
        List<Material__c> materiales = new List<Material__c>();
        
        Product2 p1= TestDataFactory.getProductos().values().get(0);
        Product2 p2= TestDataFactory.getProductos().values().get(1);

        BusinessSite__c b1= TestDataFactory.getBusinessSites().values().get(0);
        BusinessSite__c b2= TestDataFactory.getBusinessSites().values().get(1);

        materiales.add( new Material__c( Serial__c = '1', NMU__c =  p1.NMU__c, Werks__c = b1.Werks__c) );
        materiales.add( new Material__c( Serial__c = '2', NMU__c =  p2.NMU__c, Werks__c = b2.Werks__c) );
        
        insert materiales;

        List<Inventory__c> inventarios = [SELECT Product__r.NMU__c, BusinessSite__r.Werks__c, Available__c, Total__c FROM Inventory__c];
        System.debug(inventarios);

    }

    static void testMoveMaterialesEntreSucursales() {

    }

    static void testCambiarNMU() {

    }

}