force-app/main/default/objects/BusinessSite__c/BusinessSite__c.object-meta.xml
<CustomObject>
    <label>Punto de Venta</label>
    <nameField>
        <label>Business Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Puntos de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BusinessSite__c/fields/Werks__c.field-meta.xml
<CustomField>
    <fullName>Werks__c</fullName>
    <label>Werks</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <description>Objeto que contiene cantidad total, reservas, muletos y disponibles de cada Punto de Venta / NMU</description>
    <label>Inventario</label>
    <nameField>
        <label>Werks y Nmu</label>
    </nameField>
    <pluralLabel>Inventarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/BusinessSite__c.field-meta.xml
<CustomField>
    <fullName>BusinessSite__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup a Business Site</description>
    <label>Punto de Venta</label>
    <referenceTo>BusinessSite__c</referenceTo>
    <relationshipLabel>Inventories</relationshipLabel>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/LockedByQuantity__c.field-meta.xml
<CustomField>
    <fullName>LockedByQuantity__c</fullName>
    <label>Bloqueos por Cantidad</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/mtpl__c.field-meta.xml
<CustomField>
    <fullName>mtpl__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad disponible</description>
    <label>Disponibles</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/mtpm__c.field-meta.xml
<CustomField>
    <fullName>mtpm__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Muletos</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/mtre__c.field-meta.xml
<CustomField>
    <fullName>mtre__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bloqueos Unitarios</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup a Product</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <description>Cantidad total de materiales del NMU / Punto de venta</description>
    <label>Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NMU__c.field-meta.xml
<CustomField>
    <fullName>NMU__c</fullName>
    <label>NMU</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InventoryService.cls
public with sharing class InventoryService {
    private static String query = 'SELECT Id, Name, BusinessSite__c, Product__c,Total__c, mtpl__c, LockedByQuantity__c, mtre__c, mtpm__c FROM Inventory__c';

    public static List<Inventory__c> GetAvailabilityByWerks(String werks) {
        List<Inventory__c> listaInventario = new List<Inventory__c>();

        try {
            if (String.isNotBlank(werks)) {
                query += ' WHERE BusinessSite__r.Werks__c = :werks';
            }

            listaInventario = Database.query(query);
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, 'Error en el servicio');
        }

        return listaInventario;
    }

    public static List<Inventory__c> GetAvailabilityByWerksAndNmu (String werks, String nmu) {
        List<Inventory__c> listaInventario = new List<Inventory__c>();

        try {
            if (String.isNotBlank(werks) && String.isNotBlank(nmu)) {
                query += ' WHERE BusinessSite__r.Werks__c = :werks AND Product__r.NMU__c = : nmu';

                listaInventario = Database.query(query);
            }
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR,'Error en el servicio');
        }

        return listaInventario;
    }

}